bcrypt/config/routes.rb
Rails.application.routes.draw do
  
  root to: 'articles#index'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/logout' => 'sessions#destroy'

  resources :users
  resources :sessions

end

bcrypt/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      
    end
  end

end

bcrypt/app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password

  validates_uniqueness_of :email

end

bcrypt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #protect_from_forgery
  #load_and_authorize_resource

  
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
  
end

bcrypt/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  #before_filter :authorize, only: [:edit, :update]
end

bcrypt/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

bcrypt/app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/', :alert => exception.message
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    if current_user.nil?
      redirect_to root_path, notice: "You need to be logged in to see this page."
    else
      @user = User.new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up"
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:admin, :name, :email, :password, :password_confirmation)
  end

end

bcrypt/app/helpers/application_helper.rb
module ApplicationHelper
end

bcrypt/app/helpers/articles_helper.rb
module ArticlesHelper
end

bcrypt/app/helpers/sessions_helper.rb
module SessionsHelper
  
end

bcrypt/app/helpers/users_helper.rb
module UsersHelper
  
end

bcrypt/app/views/articles/index.html.erb
<br>
<br>
<br>
<h1>Página Inicial</h1>

bcrypt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

bcrypt/app/views/users/edit.html.erb
<h1>Edit User</h1>
 
<%= form_with(model: @user, local: true) do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :admin %><br>
    <%= form.check_box :admin %>
  </p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', users_path %>

bcrypt/app/views/users/index.html.erb
<h1>Listing Users</h1>
 
<table>
  <% @users.each do |user| %>
    <tr>
      <td>
        <label style="font-weight: bold" >ID:</label>
        <%= user.id %>
      </td>
      <td>
        <label style="font-weight: bold" >NAME:</label>
        <%= user.name %>
      </td>
      <td>
        <label style="font-weight: bold" >Admin:</label>
        <%= user.admin %>
      </td>
      <td>
        <label style="font-weight: bold" >Email:</label>
        <%= user.email %>
      </td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table>

bcrypt/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

bcrypt/app/views/users/show.html.erb
<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<td><%= link_to 'Users', users_path %></td>